### ISSUE TITLE
Dependency Conflict with Werkzeug 3.0.0 in Flask 2.2.2

### ISSUE THREAD

**Issue by giovanni-norbedo** [sarusso/AutoGrading#2]
Encountering an issue due to Werkzeug 3.0.0 being installed despite Flask 2.2.2 specifying "Werkzeug>=2.2.0" in requirements. This leads to compatibility problems. 

Suggested fix is to explicitly add Werkzeug==2.2.2 in the dependencies to address this issue.

Update line 47 in "Autograding/services/webapp/Dockerfile" as follows:

From:
```docker
RUN pip install flask==2.0.2 requests==2.28.1 uwsgi==2.0.21
```

To:
```docker
RUN pip install flask==2.0.2 requests==2.28.1 uwsgi==2.0.21 Werkzeug==2.2.2
```

**Comment by sarusso** [comment]
Thanks, can you propose a pull request?

**Comment by giovanni-norbedo** [comment]
Certainly, I've submitted the pr.
